<?php
require_once('../../../classes/xajax/xajax.inc.php');
$xajax = new xajax("warehouse.server.php");
$xajax->setCharEncoding("ISO-8859-1");

$xajax->registerFunction('insertrr');
$xajax->registerFunction('insertaddr');
$xajax->registerFunction('insertcustomer');
$xajax->registerFunction('insertrrqty');
$xajax->registerFunction('updatemwrfrrno');
$xajax->registerFunction('updatemwrfrrqty');
$xajax->registerFunction('deletemwrfrr');
$xajax->registerFunction('updaterrinfo');
$xajax->registerFunction('insertsis');
$xajax->registerFunction('insertsisqty');
$xajax->registerFunction('updatesisinfo');
$xajax->registerFunction('updatesisqty');
$xajax->registerFunction('insertitemtemp');
$xajax->registerFunction('deleteitemtemp');
$xajax->registerFunction('deleteitemperm');
$xajax->registerFunction('insertnewitem');
$xajax->registerFunction('deletenewitem');
$xajax->registerFunction('updatenewitem');
$xajax->registerFunction('deselectallitem');
$xajax->registerFunction('removeallitem');
$xajax->registerFunction('insertitemrr');
$xajax->registerFunction('insertitemperma');
$xajax->registerFunction('insertitemrrinfo');
$xajax->registerFunction('updateitemrrinfo');
$xajax->registerFunction('updateitemqty');
$xajax->registerFunction('insertitemsis');
$xajax->registerFunction('updatesisitemqty');
$xajax->registerFunction('updateitembalance');
//
?>